spring.application.name=trabalhoeventos
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/sistema_eventos
spring.datasource.username=root
spring.datasource.password=van8c01n
spring.datasource.driver-class-name =com.mysql.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
